### ISSUE TITLE
Is it possible to use it with external EEPROM?

### ISSUE THREAD

**Issue by ferchinas** [amirchev/EZPROM#2]
Hi: I need to store several JSON character strings in an i2c EEPROM memory (AT24C32 of the DS3231 RTC module) connected to the ESP32.
I am interested in your library because it has the possibility of relocating the object if its size is increased (setOverwriteIfSizeDifferent).
Is it possible to use it with external memories?
Thank you

**Comment by amirchev** [comment]
Hi ferchinas, the library's written to use the internal EEPROM class. If you find all uses of the EEPROM class (which are few) and replace them with the corresponding methods of the i2c EEPROM, then it will work. Out of the box, I don't this code will not be able to use any other EEPROM except the internal one.

**Comment by amirchev** [comment]
We're you able to work it out? If not, send me a link to the library you will be using with your memory board and I will see if I can figure something out.

**Comment by roboticboyer** [comment]
A good External Eeprom library is [https://github.com/PaoloP74/extEEPROM](https://github.com/PaoloP74/extEEPROM)

**Comment by amirchev** [comment]
I will see how I can make use of that library.
