### ISSUE TITLE
Arduino Library Manager

### ISSUE THREAD

**Issue by roboticboyer** [amirchev/EZPROM#3]
The EZPROM library installed by Arduino Library Manager is not updated with the version in GitHub
There is the call to Logger.h library in .cpp and .h files

Please could you fix this issue?
Thank you
Gio

**Comment by amirchev** [comment]
Hi Gio, just released v1.1.2, does that work?

**Comment by roboticboyer** [comment]
Hi Aleksandr
Yes it works now
Thank you
Gio
