### ISSUE TITLE
LoadSerial for 1 object causes the location for a different object to be overwritten

### ISSUE THREAD

**Issue by dsilva-vd** [amirchev/EZPROM#4]
[int-eeprom-pro-mini.zip](https://github.com/amirchev/EZPROM/files/4195331/int-eeprom-pro-mini.zip)

Hi @amirchev,

I am using your EZPROM library and I have a strange bug. I think I am not using your library correctly but I cannot see where the bug is. 

I have two classes
Log_Info with array of 1 struct
Log with array of 8 structs

When I load Log Info using Load Serial it seems to overwrite one of the variables in index 0 of Log. I've included my .ino file and the serial port output.

The serial port output shows the Log value is empty before I attempt to write to memory. I perform 2 writes to Logs variable. Both times the timestamp value of index 0 of Logs variable is changed when LoadSerial(Log_info) is called. 

Thank you for your help!

**Comment by amirchev** [comment]
Hi, thanks for posting the related files, I'm looking into it right now.

**Comment by amirchev** [comment]
@dsilva-vd hey, after a few hours I found a memory leak. In your setup function, comment out these two lines:
`    logs = LogHistory();
    logs_info = LogInformation();`

These variables have already been defined, and this definition creates new pointers without freeing the memory created by the previous definition here:
`//Logging global variables
LogHistory logs;
LogInformation logs_info;
LogCfg log_config;`
