### ISSUE TITLE
no initialization checks

### ISSUE THREAD

**Issue by Vigeant** [amirchev/EZPROM#5]
It would be nice to have an initialization  check (is_initialized()) based on the presence of a magic 32bit number say at the end (near where you keep your object count)

This would allow initializing (reset()) only if not initialized already making sure the structure in the eeprom is valid on a first boot.

**Comment by amirchev** [comment]
That's a good idea. While you could theoretically accomplish this on your own, it would be nice to have this functionality as a part of reset, perhaps a flag for the reset method...

**Comment by Vigeant** [comment]
Ya and something that would survive a dirty eeprom memory that would not throw off your logic. I should probably do another issue for this but also a CRC check would be awesome. Its particularly important on eeproms as they are short lived and its nice to detect when its dying.

**Comment by Vigeant** [comment]
I do put it in my object to make sure along with a version I'd but it would
be a nice addition.

**Comment by amirchev** [comment]
Hey, see the new method #setup in v1.2.0
